"""user oidc sub

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 20:27:41.634744
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oidc_sub', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_oidc_sub'), ['oidc_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_oidc_sub'))
        batch_op.drop_column('oidc_sub')

    # ### end Alembic commands ###
