"""rule amount bounds

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 21:55:16.531032
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_min_cents', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amount_max_cents', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_column('amount_max_cents')
        batch_op.drop_column('amount_min_cents')

    # ### end Alembic commands ###
